### ISSUE TITLE
The Setup Description is incomplete (or invalid?) 

### ISSUE THREAD

**Issue by Shamane2000** [HerrHofrat/deconz-config#2]
I tried to install this script as described, but it doesn't work for me.
I created the directory "www" and insert the file "deconz-config.html" in "/config", restartet the whole system and tried first the (wrong) link from the setup description ("http:///local/deconz-config/index.html") 
but also after correcting this link to eg: "http://hassio.local:8123/deconz-config.html" it doesn't work (404 error). 
I am not successful to find any HASSIO description for using this behavior... 

I use:
RaspberryPi 1 B+ (No optional USB Stick)
System: HassOS 1.11
Deployment: production

PS: Antworten auf Deutsch wären auch recht. ;-)

**Comment by HerrHofrat** [comment]
You are totally right - the I have an error in my markdown that displays the URL wrong. Thanks for reporting! The right one is:

Du hast vollkommen recht - Markdown zeigt dir Addresse falsch an. Danke fürs benachrichtigen! Die Richtige wäre:

`http://hassio.local:8123/local/deconz-config/index.html`

**Comment by Shamane2000** [comment]
Now it works! Thanx a lot! :-) 

PS: Wie nennt sich denn das hier genutzte "Feature" von HomeAssistant?
PPS: Da ich nicht weiß, wie man in Github direkt Nachrichten schreibt frag ich vorsichtig hier nach - Gibt es noch eine dir bekannte Alternative zu dem deCONZ Addon (https://github.com/marthoc/hassio-addons) für HASS.IO, da diese bei mir nicht startet? (https://github.com/marthoc/hassio-addons/issues/24)

**Comment by HerrHofrat** [comment]
Ich glaub das Feature hat gar keinen Namen - wurde mal im Blog erwähnt (https://www.home-assistant.io/blog/2016/04/07/static-website/) und wird hauptsächlich für customization benutzt. 
Ich hab auf meinem rpi raspbian laufen und docker für hass und die addons. deconz läuft bei mir einfach direkt auf raspbian außerhalb von docker.
